const translations = {
    ru: {
        loading: "Синхронизация со звездами...",
        back: "Назад",
        to_main: "На главную",
        save: "СОХРАНИТЬ",
        cancel: "Отмена",
        delete: "Удалить",
        free: "Бесплатно",
        day: "День",
        days: "дней",
        month: "Месяц",
        year: "ГГГГ",
        nav_home: "Главная",
        nav_spreads: "Расклады",
        nav_chats: "Чаты",
        nav_shop: "Магазин",
        nav_profile: "Профиль",
        home_ready: "Звезды готовы,",
        home_wanderer: "Странник",
        daily_bonus: "Ежедневный бонус",
        bonus_desc: "Заходи каждый день",
        energy_day: "Энергия дня",
        card_day: "Твоя Карта Дня",
        card_day_desc: "Вселенная приготовила послание. Открой, чтобы узнать.",
        opportunities: "ВОЗМОЖНОСТИ",
        tarot: "Таро",
        tarot_desc: "Расклады и анализ",
        astro: "Астрология",
        astro_desc: "Натальная карта",
        dreams: "Сны",
        dreams_desc: "Толкование символов",
        cal: "Календарь",
        cal_desc: "Лунные фазы",
        spreads_title: "Расклады",
        spreads_subtitle: "Выберите подходящий расклад. ИИ-Таролог поможет прочитать послание карт.",
        spreads_basic: "БАЗОВЫЕ",
        spreads_deep: "ГЛУБИННЫЕ",
        s1_name: "Карта дня / Да-Нет",
        s1_desc: "Быстрый ответ на один вопрос",
        s2_name: "Прошлое · Настоящее · Будущее",
        s2_desc: "Развитие ситуации (3 карты)",
        s3_name: "На чувства человека",
        s3_desc: "Что он думает и чувствует (3 карты)",
        s4_name: "Кельтский крест",
        s4_desc: "Самый подробный анализ из 10 карт. Причины, следствия и итог.",
        s5_name: "Проблема выбора",
        s5_desc: "Сравнение двух вариантов. Поможет принять решение.",
        tarot_focus: "Ментальный фокус",
        tarot_arch: "Архитектура расклада",
        cards_count: "карт(ы)",
        what_to_ask: "Что ты хочешь спросить у звезд?",
        ph_question: "Опиши ситуацию или задай вопрос...",
        btn_pull_cards: "ВЫТЯНУТЬ КАРТЫ",
        shuffling: "Тасую колоду...",
        shuffling_desc: "Это занимает 15–25 секунд.<br>Не закрывай экран — карты уже выстраиваются.",
        your_question: "Твой вопрос",
        decoding: "Расшифровка Звезд",
        btn_finish: "ЗАВЕРШИТЬ РИТУАЛ",
        cal_title: "Энергия Дня",
        cal_dos: "Хорошо сегодня",
        cal_donts: "Воздержись",
        cal_beauty: "Красота и тело",
        haircut: "Стрижка",
        coloring: "Окрашивание",
        manicure: "Маникюр",
        face_care: "Косметология",
        horoscope: "Гороскоп",
        today: "Сегодня",
        sign: "Знак",
        dreams_title: "Дневник снов",
        dreams_subtitle: "Запишите свой сон. Наш ИИ, обученный на трактатах Юнга и старинных сонниках, расшифрует его символы.",
        ph_dream: "Мне приснилось, что я стою на краю обрыва...",
        btn_decode: "Расшифровать",
        chat_oracle: "Вселенский Оракул",
        chat_online: "На связи",
        quick_pred: "🔮 Предсказание",
        quick_astro: "✨ Астро-прогноз",
        ph_chat: "Спроси Оракула...",
        shop_title: "Энергия Звезд",
        shop_subtitle: "Кристаллы чистой энергии для глубоких раскладов и общения с Оракулом",
        shop_empty: "Витрина пуста",
        shop_empty_desc: "Кристаллы энергии еще формируются...",
        energy_unit: "Энергии",
        prof_with_us: "С нами с",
        prof_sign: "ЗНАК",
        prof_element: "СТИХИЯ",
        prof_planet: "ПЛАНЕТА",
        prof_streak: "ПОДРЯД",
        prof_balance: "БАЛАНС",
        ref_title: "Реферальная программа",
        ref_desc: "Приглашай друзей и получай бонусы",
        prof_settings: "НАСТРОЙКИ",
        prof_name: "Имя",
        prof_birth: "Данные рождения",
        prof_add: "Добавить",
        prof_lang: "Язык приложения",
        prof_support: "Помощь и поддержка",
        prof_terms: "Соглашение и политика",
        prof_unknown: "Неизвестно",
        bonus_welcome: "С возвращением",
        bonus_streak: "Дней в потоке",
        bonus_of: "из 7",
        bonus_keep: "Отличная инерция. Не сбавляй!",
        bonus_all: "ВСЕ НАГРАДЫ",
        bonus_claimed: "Забрано",
        bonus_claim: "Забрать",
        card_energy: "Энергия суток",
        card_pull: "Вытянуть карту",
        card_guide: "Главный Проводник Дня",
        card_time: "Час Силы",
        card_vibe: "Вибрация",
        card_sync: "Сонастрой",
        card_back: "Вернуться в созвездия",
        card_wait: "Оракул настраивает астральные частоты...",
        card_ready: "Звезды сошлись в твоей точке пространства",
        card_touch: "Коснись эфира, чтобы Оракул вытянул твой персональный Аркан и составил ментальный план.",
        lang_title: "Выбор языка",
        birth_title: "Твой день рождения",
        name_title: "Как к тебе обращаться?",
        ph_name: "Твое имя...",
        btn_save_name: "СОХРАНИТЬ ИМЯ",
        astro_title: "Космо-Паспорт",
        astro_desc: "Укажи точные данные, чтобы ИИ учитывал влияние планет.",
        time: "Время",
        dont_know: "Не знаю",
        city: "Город рождения",
        btn_calc_chart: "РАССЧИТАТЬ КАРТУ",
        ref_friends: "Твои друзья",
        ref_bonus: "Зови друзей и получай +10 энергии за каждого",
        ref_link: "Твоя ссылка",
        ref_share: "Отправить в Telegram",
        ref_invited: "Приглашенные",
        del_chat_title: "Удалить чат?",
        del_chat_desc: "Все сообщения в этой беседе будут удалены безвозвратно. Это действие нельзя отменить.",
        maint_title: "Космические перегрузки",
        maint_desc: "Связь со звездами временно прервана — сервер обновляется или база данных ушла в глубокую медитацию. Мы уже чиним! 🛠️",
        maint_btn: "НАПИСАТЬ В САППОРТ",
        toast_wait: "Связываемся со звездами...",
        toast_success: "Успешно!",
        toast_error: "Ошибка связи со звездами",
        toast_no_energy: "Недостаточно энергии!",
        toast_enter_q: "Сформулируй свой вопрос",
        toast_enter_name: "Введи имя",
        toast_enter_date: "Укажи дату полностью",
        toast_enter_city: "Укажи дату и город",
        toast_describe_dream: "Сначала опишите сон",
        toast_copied: "Ссылка скопирована!",
        toast_cleared: "Чат очищен",
        toast_lang_changed: "Язык изменён ✓"
    },
    en: {
        loading: "Syncing with the stars...",
        back: "Back",
        to_main: "To Main",
        save: "SAVE",
        cancel: "Cancel",
        delete: "Delete",
        free: "Free",
        day: "Day",
        days: "days",
        month: "Month",
        year: "YYYY",
        nav_home: "Home",
        nav_spreads: "Spreads",
        nav_chats: "Chats",
        nav_shop: "Shop",
        nav_profile: "Profile",
        home_ready: "The stars are ready,",
        home_wanderer: "Wanderer",
        daily_bonus: "Daily Bonus",
        bonus_desc: "Log in every day",
        energy_day: "Energy of the Day",
        card_day: "Your Card of the Day",
        card_day_desc: "The universe has a message for you. Open to reveal.",
        opportunities: "OPPORTUNITIES",
        tarot: "Tarot",
        tarot_desc: "Spreads and analysis",
        astro: "Astrology",
        astro_desc: "Natal chart",
        dreams: "Dreams",
        dreams_desc: "Symbol interpretation",
        cal: "Calendar",
        cal_desc: "Lunar phases",
        spreads_title: "Tarot Spreads",
        spreads_subtitle: "Choose a spread. The AI Tarot Reader will decipher the cards' message.",
        spreads_basic: "BASIC",
        spreads_deep: "DEEP ANALYSIS",
        s1_name: "Card of the Day / Yes-No",
        s1_desc: "Quick answer to a single question",
        s2_name: "Past · Present · Future",
        s2_desc: "Development of a situation (3 cards)",
        s3_name: "Someone's Feelings",
        s3_desc: "What they think and feel (3 cards)",
        s4_name: "Celtic Cross",
        s4_desc: "The most detailed 10-card analysis. Causes, effects, and outcome.",
        s5_name: "The Problem of Choice",
        s5_desc: "Comparing two paths. Helps you make a decision.",
        tarot_focus: "Mental Focus",
        tarot_arch: "Spread Architecture",
        cards_count: "card(s)",
        what_to_ask: "What do you want to ask the stars?",
        ph_question: "Describe the situation or ask a question...",
        btn_pull_cards: "DRAW CARDS",
        shuffling: "Shuffling the deck...",
        shuffling_desc: "This takes 15–25 seconds.<br>Do not close the screen — the cards are aligning.",
        your_question: "Your question",
        decoding: "Deciphering the Stars",
        btn_finish: "FINISH RITUAL",
        cal_title: "Energy of the Day",
        cal_dos: "Favorable today",
        cal_donts: "Avoid today",
        cal_beauty: "Beauty & Body",
        haircut: "Haircut",
        coloring: "Hair Coloring",
        manicure: "Manicure",
        face_care: "Skincare",
        horoscope: "Horoscope",
        today: "Today",
        sign: "Sign",
        dreams_title: "Dream Journal",
        dreams_subtitle: "Write down your dream. Our AI, trained on Jung's treatises and ancient dream books, will decipher its symbols.",
        ph_dream: "I dreamed that I was standing on the edge of a cliff...",
        btn_decode: "Decipher",
        chat_oracle: "Universal Oracle",
        chat_online: "Online",
        quick_pred: "🔮 Prediction",
        quick_astro: "✨ Astro-forecast",
        ph_chat: "Ask the Oracle...",
        shop_title: "Star Energy",
        shop_subtitle: "Crystals of pure energy for deep spreads and communing with the Oracle",
        shop_empty: "The showcase is empty",
        shop_empty_desc: "Energy crystals are still forming...",
        energy_unit: "Energy",
        prof_with_us: "With us since",
        prof_sign: "SIGN",
        prof_element: "ELEMENT",
        prof_planet: "PLANET",
        prof_streak: "STREAK",
        prof_balance: "BALANCE",
        ref_title: "Referral Program",
        ref_desc: "Invite friends and get bonuses",
        prof_settings: "SETTINGS",
        prof_name: "Name",
        prof_birth: "Birth Data",
        prof_add: "Add",
        prof_lang: "App Language",
        prof_support: "Help & Support",
        prof_terms: "Terms & Policies",
        prof_unknown: "Unknown",
        bonus_welcome: "Welcome back",
        bonus_streak: "Days in flow",
        bonus_of: "of 7",
        bonus_keep: "Great momentum. Keep it up!",
        bonus_all: "ALL REWARDS",
        bonus_claimed: "Claimed",
        bonus_claim: "Claim",
        card_energy: "Daily Energy",
        card_pull: "Draw Card",
        card_guide: "Main Guide of the Day",
        card_time: "Hour of Power",
        card_vibe: "Vibration",
        card_sync: "Alignment",
        card_back: "Return to Constellations",
        card_wait: "The Oracle is tuning astral frequencies...",
        card_ready: "The stars have aligned in your space",
        card_touch: "Touch the ether to let the Oracle draw your personal Arcana and create a mental plan for the day.",
        lang_title: "Choose Language",
        birth_title: "Your Birthday",
        name_title: "What should we call you?",
        ph_name: "Your name...",
        btn_save_name: "SAVE NAME",
        astro_title: "Cosmo-Passport",
        astro_desc: "Provide exact data so the AI can account for planetary influences.",
        time: "Time",
        dont_know: "Don't know",
        city: "City of birth",
        btn_calc_chart: "CALCULATE CHART",
        ref_friends: "Your friends",
        ref_bonus: "Invite friends and get +10 energy for each",
        ref_link: "Your link",
        ref_share: "Share in Telegram",
        ref_invited: "Invited",
        del_chat_title: "Delete chat?",
        del_chat_desc: "All messages in this conversation will be permanently deleted. This action cannot be undone.",
        maint_title: "Cosmic Overload",
        maint_desc: "Connection with the stars is temporarily interrupted — the server is updating or the database is in deep meditation. We are fixing it! 🛠️",
        maint_btn: "CONTACT SUPPORT",
        toast_wait: "Connecting to the stars...",
        toast_success: "Success!",
        toast_error: "Error connecting to the stars",
        toast_no_energy: "Not enough energy!",
        toast_enter_q: "Formulate your question",
        toast_enter_name: "Enter your name",
        toast_enter_date: "Enter the full date",
        toast_enter_city: "Enter the date and city",
        toast_describe_dream: "Describe your dream first",
        toast_copied: "Link copied!",
        toast_cleared: "Chat cleared",
        toast_lang_changed: "Language changed ✓"
    },
    es: {
        loading: "Sincronizando con las estrellas...",
        back: "Volver",
        to_main: "Al Inicio",
        save: "GUARDAR",
        cancel: "Cancelar",
        delete: "Eliminar",
        free: "Gratis",
        day: "Día",
        days: "días",
        month: "Mes",
        year: "AAAA",
        nav_home: "Inicio",
        nav_spreads: "Tiradas",
        nav_chats: "Chats",
        nav_shop: "Tienda",
        nav_profile: "Perfil",
        home_ready: "Las estrellas están listas,",
        home_wanderer: "Viajero",
        daily_bonus: "Bono Diario",
        bonus_desc: "Entra todos los días",
        energy_day: "Energía del Día",
        card_day: "Tu Carta del Día",
        card_day_desc: "El universo tiene un mensaje. Ábrelo para saber.",
        opportunities: "OPORTUNIDADES",
        tarot: "Tarot",
        tarot_desc: "Tiradas y análisis",
        astro: "Astrología",
        astro_desc: "Carta natal",
        dreams: "Sueños",
        dreams_desc: "Interpretación de símbolos",
        cal: "Calendario",
        cal_desc: "Fases lunares",
        spreads_title: "Tiradas de Tarot",
        spreads_subtitle: "Elige una tirada. El Tarotista IA descifrará el mensaje.",
        spreads_basic: "BÁSICAS",
        spreads_deep: "PROFUNDAS",
        s1_name: "Carta del Día / Sí-No",
        s1_desc: "Respuesta rápida a una pregunta",
        s2_name: "Pasado · Presente · Futuro",
        s2_desc: "Desarrollo de la situación (3 cartas)",
        s3_name: "Sentimientos",
        s3_desc: "Lo que piensa y siente (3 cartas)",
        s4_name: "Cruz Celta",
        s4_desc: "Análisis detallado de 10 cartas. Causas, efectos y resultado.",
        s5_name: "Problema de Elección",
        s5_desc: "Comparando dos caminos. Te ayuda a decidir.",
        tarot_focus: "Enfoque Mental",
        tarot_arch: "Arquitectura de Tirada",
        cards_count: "carta(s)",
        what_to_ask: "¿Qué quieres preguntar a las estrellas?",
        ph_question: "Describe la situación o haz una pregunta...",
        btn_pull_cards: "SACAR CARTAS",
        shuffling: "Barajando el mazo...",
        shuffling_desc: "Esto toma 15–25 segundos.<br>No cierres la pantalla — las cartas se están alineando.",
        your_question: "Tu pregunta",
        decoding: "Descifrando Estrellas",
        btn_finish: "FINALIZAR RITUAL",
        cal_title: "Energía del Día",
        cal_dos: "Favorable hoy",
        cal_donts: "Evitar hoy",
        cal_beauty: "Belleza y Cuerpo",
        haircut: "Corte de pelo",
        coloring: "Coloración",
        manicure: "Manicura",
        face_care: "Cuidado facial",
        horoscope: "Horóscopo",
        today: "Hoy",
        sign: "Signo",
        dreams_title: "Diario de Sueños",
        dreams_subtitle: "Escribe tu sueño. Nuestra IA, entrenada en Jung, descifrará sus símbolos.",
        ph_dream: "Soñé que estaba de pie al borde de un acantilado...",
        btn_decode: "Descifrar",
        chat_oracle: "Oráculo Universal",
        chat_online: "En línea",
        quick_pred: "🔮 Predicción",
        quick_astro: "✨ Pronóstico Astro",
        ph_chat: "Pregunta al Oráculo...",
        shop_title: "Energía Estelar",
        shop_subtitle: "Cristales de energía pura para tiradas profundas y hablar con el Oráculo",
        shop_empty: "La vitrina está vacía",
        shop_empty_desc: "Los cristales de energía aún se están formando...",
        energy_unit: "Energía",
        prof_with_us: "Con nosotros desde",
        prof_sign: "SIGNO",
        prof_element: "ELEMENTO",
        prof_planet: "PLANETA",
        prof_streak: "RACHA",
        prof_balance: "SALDO",
        ref_title: "Programa de Referidos",
        ref_desc: "Invita amigos y obtén bonos",
        prof_settings: "AJUSTES",
        prof_name: "Nombre",
        prof_birth: "Datos de Nacimiento",
        prof_add: "Añadir",
        prof_lang: "Idioma de la App",
        prof_support: "Ayuda y Soporte",
        prof_terms: "Términos y Políticas",
        prof_unknown: "Desconocido",
        bonus_welcome: "Bienvenido de nuevo",
        bonus_streak: "Días en flujo",
        bonus_of: "de 7",
        bonus_keep: "Gran inercia. ¡Sigue así!",
        bonus_all: "RECOMPENSAS",
        bonus_claimed: "Reclamado",
        bonus_claim: "Reclamar",
        card_energy: "Energía Diaria",
        card_pull: "Sacar Carta",
        card_guide: "Guía Principal del Día",
        card_time: "Hora de Poder",
        card_vibe: "Vibración",
        card_sync: "Sintonía",
        card_back: "Volver a Constelaciones",
        card_wait: "El Oráculo ajusta las frecuencias astrales...",
        card_ready: "Las estrellas se han alineado en tu espacio",
        card_touch: "Toca el éter para que el Oráculo saque tu Arcano personal.",
        lang_title: "Elige el Idioma",
        birth_title: "Tu Cumpleaños",
        name_title: "¿Cómo deberíamos llamarte?",
        ph_name: "Tu nombre...",
        btn_save_name: "GUARDAR NOMBRE",
        astro_title: "Cosmo-Pasaporte",
        astro_desc: "Proporciona datos exactos para considerar influencias planetarias.",
        time: "Hora",
        dont_know: "No lo sé",
        city: "Ciudad de nacimiento",
        btn_calc_chart: "CALCULAR CARTA",
        ref_friends: "Tus amigos",
        ref_bonus: "Invita amigos y recibe +10 de energía por cada uno",
        ref_link: "Tu enlace",
        ref_share: "Compartir en Telegram",
        ref_invited: "Invitados",
        del_chat_title: "¿Eliminar chat?",
        del_chat_desc: "Todos los mensajes se eliminarán permanentemente. No se puede deshacer.",
        maint_title: "Sobrecarga Cósmica",
        maint_desc: "Conexión interrumpida temporalmente. ¡Lo estamos arreglando! 🛠️",
        maint_btn: "CONTACTAR SOPORTE",
        toast_wait: "Conectando con las estrellas...",
        toast_success: "¡Éxito!",
        toast_error: "Error de conexión",
        toast_no_energy: "¡No hay suficiente energía!",
        toast_enter_q: "Formula tu pregunta",
        toast_enter_name: "Introduce tu nombre",
        toast_enter_date: "Introduce la fecha",
        toast_enter_city: "Introduce fecha y ciudad",
        toast_describe_dream: "Describe tu sueño primero",
        toast_copied: "¡Enlace copiado!",
        toast_cleared: "Chat borrado",
        toast_lang_changed: "Idioma cambiado ✓"
    },
    fr: {
        loading: "Synchronisation...",
        back: "Retour",
        to_main: "Accueil",
        save: "ENREGISTRER",
        cancel: "Annuler",
        delete: "Supprimer",
        free: "Gratuit",
        day: "Jour",
        days: "jours",
        month: "Mois",
        year: "AAAA",
        nav_home: "Accueil",
        nav_spreads: "Tirages",
        nav_chats: "Chats",
        nav_shop: "Boutique",
        nav_profile: "Profil",
        home_ready: "Les étoiles sont prêtes,",
        home_wanderer: "Voyageur",
        daily_bonus: "Bonus Quotidien",
        bonus_desc: "Connectez-vous tous les jours",
        energy_day: "Énergie du Jour",
        card_day: "Votre Carte du Jour",
        card_day_desc: "L'univers a un message. Ouvrez pour le découvrir.",
        opportunities: "OPPORTUNITÉS",
        tarot: "Tarot",
        tarot_desc: "Tirages et analyse",
        astro: "Astrologie",
        astro_desc: "Thème astral",
        dreams: "Rêves",
        dreams_desc: "Interprétation de symboles",
        cal: "Calendrier",
        cal_desc: "Phases lunaires",
        spreads_title: "Tirages de Tarot",
        spreads_subtitle: "Choisissez un tirage. Le Tarologue IA déchiffrera le message.",
        spreads_basic: "BASIQUES",
        spreads_deep: "PROFONDS",
        s1_name: "Carte du Jour / Oui-Non",
        s1_desc: "Réponse rapide à une question",
        s2_name: "Passé · Présent · Futur",
        s2_desc: "Évolution de la situation (3 cartes)",
        s3_name: "Les Sentiments",
        s3_desc: "Ce qu'il pense et ressent (3 cartes)",
        s4_name: "Croix Celtique",
        s4_desc: "Analyse détaillée de 10 cartes. Causes, effets et résultat.",
        s5_name: "Le Problème du Choix",
        s5_desc: "Comparer deux chemins. Vous aide à décider.",
        tarot_focus: "Concentration Mentale",
        tarot_arch: "Architecture du Tirage",
        cards_count: "carte(s)",
        what_to_ask: "Que voulez-vous demander aux étoiles ?",
        ph_question: "Décrivez la situation ou posez une question...",
        btn_pull_cards: "TIRER LES CARTES",
        shuffling: "Mélange des cartes...",
        shuffling_desc: "Cela prend 15 à 25 secondes.<br>Ne fermez pas l'écran — les cartes s'alignent.",
        your_question: "Votre question",
        decoding: "Déchiffrement des Étoiles",
        btn_finish: "TERMINER LE RITUEL",
        cal_title: "Énergie du Jour",
        cal_dos: "Favorable aujourd'hui",
        cal_donts: "À éviter aujourd'hui",
        cal_beauty: "Beauté & Corps",
        haircut: "Coupe de cheveux",
        coloring: "Coloration",
        manicure: "Manucure",
        face_care: "Soins du visage",
        horoscope: "Horoscope",
        today: "Aujourd'hui",
        sign: "Signe",
        dreams_title: "Journal des Rêves",
        dreams_subtitle: "Écrivez votre rêve. Notre IA, formée sur Jung, déchiffrera ses symboles.",
        ph_dream: "J'ai rêvé que je me tenais au bord d'une falaise...",
        btn_decode: "Déchiffrer",
        chat_oracle: "Oracle Universel",
        chat_online: "En ligne",
        quick_pred: "🔮 Prédiction",
        quick_astro: "✨ Prévisions Astro",
        ph_chat: "Demandez à l'Oracle...",
        shop_title: "Énergie Stellaire",
        shop_subtitle: "Cristaux d'énergie pure pour des tirages profonds",
        shop_empty: "La vitrine est vide",
        shop_empty_desc: "Les cristaux d'énergie sont encore en formation...",
        energy_unit: "Énergie",
        prof_with_us: "Avec nous depuis",
        prof_sign: "SIGNE",
        prof_element: "ÉLÉMENT",
        prof_planet: "PLANÈTE",
        prof_streak: "SÉRIE",
        prof_balance: "SOLDE",
        ref_title: "Programme de Parrainage",
        ref_desc: "Invitez des amis et obtenez des bonus",
        prof_settings: "PARAMÈTRES",
        prof_name: "Nom",
        prof_birth: "Données de Naissance",
        prof_add: "Ajouter",
        prof_lang: "Langue de l'App",
        prof_support: "Aide & Support",
        prof_terms: "Conditions et Politiques",
        prof_unknown: "Inconnu",
        bonus_welcome: "Bon retour",
        bonus_streak: "Jours en flux",
        bonus_of: "sur 7",
        bonus_keep: "Excellente dynamique. Continuez !",
        bonus_all: "RÉCOMPENSAS",
        bonus_claimed: "Réclamé",
        bonus_claim: "Réclamer",
        card_energy: "Énergie Quotidienne",
        card_pull: "Tirer la Carte",
        card_guide: "Guide Principal du Jour",
        card_time: "Heure de Pouvoir",
        card_vibe: "Vibration",
        card_sync: "Alignement",
        card_back: "Retour aux Constellations",
        card_wait: "L'Oracle ajuste les fréquences astrales...",
        card_ready: "Les étoiles se sont alignées",
        card_touch: "Touchez l'éther pour que l'Oracle tire votre Arcane personnel.",
        lang_title: "Choisissez la Langue",
        birth_title: "Votre Anniversaire",
        name_title: "Comment devrions-nous vous appeler ?",
        ph_name: "Votre nom...",
        btn_save_name: "ENREGISTRER LE NOM",
        astro_title: "Cosmo-Passeport",
        astro_desc: "Fournissez des données exactes pour l'IA.",
        time: "Heure",
        dont_know: "Je ne sais pas",
        city: "Ville de naissance",
        btn_calc_chart: "CALCULER LE THÈME",
        ref_friends: "Vos amis",
        ref_bonus: "Invitez des amis et recevez +10 d'énergie pour chacun",
        ref_link: "Votre lien",
        ref_share: "Partager sur Telegram",
        ref_invited: "Invités",
        del_chat_title: "Supprimer le chat ?",
        del_chat_desc: "Tous les messages seront définitivement supprimés.",
        maint_title: "Surcharge Cosmique",
        maint_desc: "Connexion interrompue temporairement. Nous réparons cela ! 🛠️",
        maint_btn: "CONTACTER LE SUPPORT",
        toast_wait: "Connexion aux étoiles...",
        toast_success: "Succès !",
        toast_error: "Erreur de connexion",
        toast_no_energy: "Pas assez d'énergie !",
        toast_enter_q: "Formulez votre question",
        toast_enter_name: "Entrez votre nom",
        toast_enter_date: "Entrez la date",
        toast_enter_city: "Entrez date et ville",
        toast_describe_dream: "Décrivez d'abord votre rêve",
        toast_copied: "Lien copié !",
        toast_cleared: "Chat effacé",
        toast_lang_changed: "Langue modifiée ✓"
    },
    de: {
        loading: "Synchronisation...",
        back: "Zurück",
        to_main: "Zur Startseite",
        save: "SPEICHERN",
        cancel: "Abbrechen",
        delete: "Löschen",
        free: "Kostenlos",
        day: "Tag",
        days: "Tage",
        month: "Monat",
        year: "JJJJ",
        nav_home: "Startseite",
        nav_spreads: "Legungen",
        nav_chats: "Chats",
        nav_shop: "Shop",
        nav_profile: "Profil",
        home_ready: "Die Sterne sind bereit,",
        home_wanderer: "Wanderer",
        daily_bonus: "Täglicher Bonus",
        bonus_desc: "Logge dich jeden Tag ein",
        energy_day: "Energie des Tages",
        card_day: "Deine Tageskarte",
        card_day_desc: "Das Universum hat eine Nachricht. Öffnen, um sie zu sehen.",
        opportunities: "MÖGLICHKEITEN",
        tarot: "Tarot",
        tarot_desc: "Legungen und Analysen",
        astro: "Astrologie",
        astro_desc: "Geburtshoroskop",
        dreams: "Träume",
        dreams_desc: "Symboldeutung",
        cal: "Kalender",
        cal_desc: "Mondphasen",
        spreads_title: "Tarot-Legungen",
        spreads_subtitle: "Wähle eine Legung. Der KI-Tarotleser entschlüsselt die Nachricht.",
        spreads_basic: "BASIS",
        spreads_deep: "TIEFGRÜNDIG",
        s1_name: "Tageskarte / Ja-Nein",
        s1_desc: "Schnelle Antwort auf eine Frage",
        s2_name: "Vergangenheit · Gegenwart · Zukunft",
        s2_desc: "Entwicklung der Situation (3 Karten)",
        s3_name: "Gefühle einer Person",
        s3_desc: "Was sie denkt und fühlt (3 Karten)",
        s4_name: "Keltisches Kreuz",
        s4_desc: "Detaillierte Analyse von 10 Karten. Ursachen, Wirkungen und Ergebnis.",
        s5_name: "Das Problem der Wahl",
        s5_desc: "Zwei Wege vergleichen. Hilft bei der Entscheidung.",
        tarot_focus: "Mentaler Fokus",
        tarot_arch: "Struktur der Legung",
        cards_count: "Karte(n)",
        what_to_ask: "Was möchtest du die Sterne fragen?",
        ph_question: "Beschreibe die Situation oder stelle eine Frage...",
        btn_pull_cards: "KARTEN ZIEHEN",
        shuffling: "Mische das Deck...",
        shuffling_desc: "Das dauert 15–25 Sekunden.<br>Schließe nicht den Bildschirm — die Karten richten sich aus.",
        your_question: "Deine Frage",
        decoding: "Sterne entschlüsseln",
        btn_finish: "RITUAL BEENDEN",
        cal_title: "Energie des Tages",
        cal_dos: "Günstig heute",
        cal_donts: "Heute vermeiden",
        cal_beauty: "Schönheit & Körper",
        haircut: "Haarschnitt",
        coloring: "Haare färben",
        manicure: "Maniküre",
        face_care: "Gesichtspflege",
        horoscope: "Horoskop",
        today: "Heute",
        sign: "Sternzeichen",
        dreams_title: "Traum-Tagebuch",
        dreams_subtitle: "Schreibe deinen Traum auf. Unsere KI wird seine Symbole entschlüsseln.",
        ph_dream: "Ich träumte, ich stünde am Rand einer Klippe...",
        btn_decode: "Entschlüsseln",
        chat_oracle: "Universelles Orakel",
        chat_online: "Online",
        quick_pred: "🔮 Vorhersage",
        quick_astro: "✨ Astro-Prognose",
        ph_chat: "Frag das Orakel...",
        shop_title: "Sternenenergie",
        shop_subtitle: "Kristalle reiner Energie für tiefe Legungen",
        shop_empty: "Die Vitrine ist leer",
        shop_empty_desc: "Energiekristalle bilden sich noch...",
        energy_unit: "Energie",
        prof_with_us: "Bei uns seit",
        prof_sign: "ZEICHEN",
        prof_element: "ELEMENT",
        prof_planet: "PLANET",
        prof_streak: "STREAK",
        prof_balance: "GUTHABEN",
        ref_title: "Empfehlungsprogramm",
        ref_desc: "Lade Freunde ein und erhalte Boni",
        prof_settings: "EINSTELLUNGEN",
        prof_name: "Name",
        prof_birth: "Geburtsdaten",
        prof_add: "Hinzufügen",
        prof_lang: "App-Sprache",
        prof_support: "Hilfe & Support",
        prof_terms: "Bedingungen und Richtlinien",
        prof_unknown: "Unbekannt",
        bonus_welcome: "Willkommen zurück",
        bonus_streak: "Tage im Fluss",
        bonus_of: "von 7",
        bonus_keep: "Tolle Dynamik. Mach weiter so!",
        bonus_all: "BELOHNUNGEN",
        bonus_claimed: "Beansprucht",
        bonus_claim: "Beanspruchen",
        card_energy: "Tagesenergie",
        card_pull: "Karte ziehen",
        card_guide: "Hauptleitfaden des Tages",
        card_time: "Stunde der Macht",
        card_vibe: "Schwingung",
        card_sync: "Ausrichtung",
        card_back: "Zurück zu den Konstellationen",
        card_wait: "Das Orakel stellt astrale Frequenzen ein...",
        card_ready: "Die Sterne haben sich ausgerichtet",
        card_touch: "Berühre den Äther, damit das Orakel deine persönliche Arkana zieht.",
        lang_title: "Sprache wählen",
        birth_title: "Dein Geburtstag",
        name_title: "Wie sollen wir dich nennen?",
        ph_name: "Dein Name...",
        btn_save_name: "NAME SPEICHERN",
        astro_title: "Kosmo-Pass",
        astro_desc: "Gib genaue Daten für die KI an.",
        time: "Zeit",
        dont_know: "Weiß ich nicht",
        city: "Geburtsstadt",
        btn_calc_chart: "HOROSKOP BERECHNEN",
        ref_friends: "Deine Freunde",
        ref_bonus: "Lade Freunde ein und erhalte +10 Energie für jeden",
        ref_link: "Dein Link",
        ref_share: "In Telegram teilen",
        ref_invited: "Eingeladen",
        del_chat_title: "Chat löschen?",
        del_chat_desc: "Alle Nachrichten werden dauerhaft gelöscht.",
        maint_title: "Kosmische Überlastung",
        maint_desc: "Verbindung vorübergehend unterbrochen. Wir beheben das! 🛠️",
        maint_btn: "SUPPORT KONTAKTIEREN",
        toast_wait: "Verbindung zu den Sternen...",
        toast_success: "Erfolg!",
        toast_error: "Verbindungsfehler",
        toast_no_energy: "Nicht genug Energie!",
        toast_enter_q: "Formuliere deine Frage",
        toast_enter_name: "Gib deinen Namen ein",
        toast_enter_date: "Gib das Datum ein",
        toast_enter_city: "Datum und Stadt eingeben",
        toast_describe_dream: "Beschreibe zuerst deinen Traum",
        toast_copied: "Link kopiert!",
        toast_cleared: "Chat gelöscht",
        toast_lang_changed: "Sprache geändert ✓"
    }
};
