const translations = {
    ru: {
        loading: "Синхронизация со звездами...",
        back: "Назад",
        to_main: "На главную",
        save: "СОХРАНИТЬ",
        cancel: "Отмена",
        delete: "Удалить",
        free: "Бесплатно",
        day: "День",
        days: "дней",
        month: "Месяц",
        year: "ГГГГ",
        nav_home: "Главная",
        nav_spreads: "Расклады",
        nav_chats: "Чаты",
        nav_shop: "Магазин",
        nav_profile: "Профиль",
        lunar_day_badge: "лун. день",
        home_ready: "Звезды готовы,",
        home_wanderer: "Странник",
        daily_bonus: "Ежедневный бонус",
        bonus_desc: "Заходи каждый день",
        energy_day: "Энергия дня",
        card_day: "Твоя Карта Дня",
        card_day_desc: "Вселенная приготовила послание. Открой, чтобы узнать.",
        opportunities: "ВОЗМОЖНОСТИ",
        tarot: "Таро",
        tarot_desc: "Расклады и анализ",
        astro: "Астрология",
        astro_desc: "Натальная карта",
        dreams: "Сны",
        dreams_desc: "Толкование символов",
        cal: "Календарь",
        cal_desc: "Лунные фазы",
        spreads_title: "Расклады",
        spreads_subtitle: "Выберите подходящий расклад. ИИ-Таролог поможет прочитать послание карт.",
        spreads_basic: "БАЗОВЫЕ",
        spreads_deep: "ГЛУБИННЫЕ",
        s1_name: "Карта дня / Да-Нет",
        s1_desc: "Быстрый ответ на один вопрос",
        s2_name: "Прошлое · Настоящее · Будущее",
        s2_desc: "Развитие ситуации (3 карты)",
        s3_name: "На чувства человека",
        toast_invalid_date: "Некорректная дата. Проверь числа!",
        s3_desc: "Что он думает и чувствует (3 карты)",
        s4_name: "Кельтский крест",
        s4_desc: "Самый подробный анализ из 10 карт. Причины, следствия и итог.",
        s5_name: "Проблема выбора",
        s5_desc: "Сравнение двух вариантов. Поможет принять решение.",
        tarot_focus: "Ментальный фокус",
        tarot_arch: "Архитектура расклада",
        cards_count: "карт(ы)",
        what_to_ask: "Что ты хочешь спросить у звезд?",
        ph_question: "Опиши ситуацию или задай вопрос...",
        btn_pull_cards: "ВЫТЯНУТЬ КАРТЫ",
        shuffling: "Тасую колоду...",
        shuffling_desc: "Это занимает 15–25 секунд.<br>Не закрывай экран — карты уже выстраиваются.",
        your_question: "Твой вопрос",
        decoding: "Расшифровка Звезд",
        btn_finish: "ЗАВЕРШИТЬ РИТУАЛ",
        cal_title: "Энергия Дня",
        cal_dos: "Хорошо сегодня",
        cal_donts: "Воздержись",
        cal_beauty: "Красота и тело",
        haircut: "Стрижка",
        coloring: "Окрашивание",
        manicure: "Маникюр",
        face_care: "Косметология",
        horoscope: "Гороскоп",
        today: "Сегодня",
        sign: "Знак",
        dreams_title: "Дневник снов",
        dreams_subtitle: "Запишите свой сон. Наш ИИ, обученный на трактатах Юнга и старинных сонниках, расшифрует его символы.",
        ph_dream: "Мне приснилось, что я стою на краю обрыва...",
        btn_decode: "Расшифровать",
        chat_oracle: "Вселенский Оракул",
        chat_online: "На связи",
        quick_pred: "🔮 Предсказание",
        quick_astro: "✨ Астро-прогноз",
        ph_chat: "Спроси Оракула...",
        shop_title: "Энергия Звезд",
        shop_subtitle: "Кристаллы чистой энергии для глубоких раскладов и общения с Оракулом",
        shop_empty: "Витрина пуста",
        shop_empty_desc: "Кристаллы энергии еще формируются...",
        energy_unit: "Энергии",
        prof_with_us: "С нами с",
        prof_sign: "ЗНАК",
        prof_element: "СТИХИЯ",
        prof_planet: "ПЛАНЕТА",
        prof_streak: "ПОДРЯД",
        prof_balance: "БАЛАНС",
        ref_title: "Реферальная программа",
        ref_desc: "Приглашай друзей и получай бонусы",
        prof_settings: "НАСТРОЙКИ",
        prof_name: "Имя",
        prof_birth: "Данные рождения",
        prof_add: "Добавить",
        prof_lang: "Язык приложения",
        prof_support: "Помощь и поддержка",
        prof_terms: "Соглашение и политика",
        prof_unknown: "Неизвестно",
        bonus_welcome: "С возвращением",
        bonus_streak: "Дней в потоке",
        bonus_of: "из 7",
        bonus_keep: "Отличная инерция. Не сбавляй!",
        bonus_all: "ВСЕ НАГРАДЫ",
        bonus_claimed: "Забрано",
        bonus_claim: "Забрать",
        card_energy: "Энергия суток",
        card_pull: "Вытянуть карту",
        card_guide: "Главный Проводник Дня",
        card_time: "Час Силы",
        card_vibe: "Вибрация",
        card_sync: "Сонастрой",
        card_back: "Вернуться в созвездия",
        card_wait: "Оракул настраивает астральные частоты...",
        card_ready: "Звезды сошлись в твоей точке пространства",
        card_touch: "Коснись эфира, чтобы Оракул вытянул твой персональный Аркан и составил ментальный план.",
        lang_title: "Выбор языка",
        birth_title: "Твой день рождения",
        name_title: "Как к тебе обращаться?",
        ph_name: "Твое имя...",
        btn_save_name: "СОХРАНИТЬ ИМЯ",
        astro_title: "Космо-Паспорт",
        astro_desc: "Укажи точные данные, чтобы ИИ учитывал влияние планет.",
        time: "Время",
        dont_know: "Не знаю",
        city: "Город рождения",
        btn_calc_chart: "РАССЧИТАТЬ КАРТУ",
        ref_friends: "Твои друзья",
        ref_bonus: "Зови друзей и получай +3 энергии за каждого",
        ref_link: "Твоя ссылка",
        ref_share: "Отправить в Telegram",
        ref_invited: "Приглашенные",
        del_chat_title: "Удалить чат?",
        del_chat_desc: "Все сообщения в этой беседе будут удалены безвозвратно. Это действие нельзя отменить.",
        maint_title: "Космические перегрузки",
        maint_desc: "Связь со звездами временно прервана — сервер обновляется или база данных ушла в глубокую медитацию. Мы уже чиним! 🛠️",
        maint_btn: "НАПИСАТЬ В САППОРТ",
        toast_wait: "Связываемся со звездами...",
        toast_success: "Успешно!",
        toast_error: "Ошибка связи со звездами",
        toast_no_energy: "Недостаточно энергии!",
        toast_enter_q: "Сформулируй свой вопрос",
        toast_enter_name: "Введи имя",
        toast_enter_date: "Укажи дату полностью",
        toast_enter_city: "Укажи дату и город",
        toast_describe_dream: "Сначала опишите сон",
        toast_copied: "Ссылка скопирована!",
        toast_cleared: "Чат очищен",
        toast_lang_changed: "Язык изменён ✓"
    },
    en: {
        loading: "Syncing with the stars...",
        back: "Back",
        to_main: "To Main",
        save: "SAVE",
        cancel: "Cancel",
        delete: "Delete",
        free: "Free",
        day: "Day",
        days: "days",
        month: "Month",
        year: "YYYY",
        nav_home: "Home",
        nav_spreads: "Spreads",
        nav_chats: "Chats",
        nav_shop: "Shop",
        lunar_day_badge: "lunar day",
        nav_profile: "Profile",
        toast_invalid_date: "Invalid date. Check the numbers!",
        home_ready: "The stars are ready,",
        home_wanderer: "Wanderer",
        daily_bonus: "Daily Bonus",
        bonus_desc: "Log in every day",
        energy_day: "Energy of the Day",
        card_day: "Your Card of the Day",
        card_day_desc: "The universe has a message for you. Open to reveal.",
        opportunities: "OPPORTUNITIES",
        tarot: "Tarot",
        tarot_desc: "Spreads and analysis",
        astro: "Astrology",
        astro_desc: "Natal chart",
        dreams: "Dreams",
        dreams_desc: "Symbol interpretation",
        cal: "Calendar",
        cal_desc: "Lunar phases",
        spreads_title: "Tarot Spreads",
        spreads_subtitle: "Choose a spread. The AI Tarot Reader will decipher the cards' message.",
        spreads_basic: "BASIC",
        spreads_deep: "DEEP ANALYSIS",
        s1_name: "Card of the Day / Yes-No",
        s1_desc: "Quick answer to a single question",
        s2_name: "Past · Present · Future",
        s2_desc: "Development of a situation (3 cards)",
        s3_name: "Someone's Feelings",
        s3_desc: "What they think and feel (3 cards)",
        s4_name: "Celtic Cross",
        s4_desc: "The most detailed 10-card analysis. Causes, effects, and outcome.",
        s5_name: "The Problem of Choice",
        s5_desc: "Comparing two paths. Helps you make a decision.",
        tarot_focus: "Mental Focus",
        tarot_arch: "Spread Architecture",
        cards_count: "card(s)",
        what_to_ask: "What do you want to ask the stars?",
        ph_question: "Describe the situation or ask a question...",
        btn_pull_cards: "DRAW CARDS",
        shuffling: "Shuffling the deck...",
        shuffling_desc: "This takes 15–25 seconds.<br>Do not close the screen — the cards are aligning.",
        your_question: "Your question",
        decoding: "Deciphering the Stars",
        btn_finish: "FINISH RITUAL",
        cal_title: "Energy of the Day",
        cal_dos: "Favorable today",
        cal_donts: "Avoid today",
        cal_beauty: "Beauty & Body",
        haircut: "Haircut",
        coloring: "Hair Coloring",
        manicure: "Manicure",
        face_care: "Skincare",
        horoscope: "Horoscope",
        today: "Today",
        sign: "Sign",
        dreams_title: "Dream Journal",
        dreams_subtitle: "Write down your dream. Our AI, trained on Jung's treatises and ancient dream books, will decipher its symbols.",
        ph_dream: "I dreamed that I was standing on the edge of a cliff...",
        btn_decode: "Decipher",
        chat_oracle: "Universal Oracle",
        chat_online: "Online",
        quick_pred: "🔮 Prediction",
        quick_astro: "✨ Astro-forecast",
        ph_chat: "Ask the Oracle...",
        shop_title: "Star Energy",
        shop_subtitle: "Crystals of pure energy for deep spreads and communing with the Oracle",
        shop_empty: "The showcase is empty",
        shop_empty_desc: "Energy crystals are still forming...",
        energy_unit: "Energy",
        prof_with_us: "With us since",
        prof_sign: "SIGN",
        prof_element: "ELEMENT",
        prof_planet: "PLANET",
        prof_streak: "STREAK",
        prof_balance: "BALANCE",
        ref_title: "Referral Program",
        ref_desc: "Invite friends and get bonuses",
        prof_settings: "SETTINGS",
        prof_name: "Name",
        prof_birth: "Birth Data",
        prof_add: "Add",
        prof_lang: "App Language",
        prof_support: "Help & Support",
        prof_terms: "Terms & Policies",
        prof_unknown: "Unknown",
        bonus_welcome: "Welcome back",
        bonus_streak: "Days in flow",
        bonus_of: "of 7",
        bonus_keep: "Great momentum. Keep it up!",
        bonus_all: "ALL REWARDS",
        bonus_claimed: "Claimed",
        bonus_claim: "Claim",
        card_energy: "Daily Energy",
        card_pull: "Draw Card",
        card_guide: "Main Guide of the Day",
        card_time: "Hour of Power",
        card_vibe: "Vibration",
        card_sync: "Alignment",
        card_back: "Return to Constellations",
        card_wait: "The Oracle is tuning astral frequencies...",
        card_ready: "The stars have aligned in your space",
        card_touch: "Touch the ether to let the Oracle draw your personal Arcana and create a mental plan for the day.",
        lang_title: "Choose Language",
        birth_title: "Your Birthday",
        name_title: "What should we call you?",
        ph_name: "Your name...",
        btn_save_name: "SAVE NAME",
        astro_title: "Cosmo-Passport",
        astro_desc: "Provide exact data so the AI can account for planetary influences.",
        time: "Time",
        dont_know: "Don't know",
        city: "City of birth",
        btn_calc_chart: "CALCULATE CHART",
        ref_friends: "Your friends",
        ref_bonus: "Invite friends and get +3 energy for each",
        ref_link: "Your link",
        ref_share: "Share in Telegram",
        ref_invited: "Invited",
        del_chat_title: "Delete chat?",
        del_chat_desc: "All messages in this conversation will be permanently deleted. This action cannot be undone.",
        maint_title: "Cosmic Overload",
        maint_desc: "Connection with the stars is temporarily interrupted — the server is updating or the database is in deep meditation. We are fixing it! 🛠️",
        maint_btn: "CONTACT SUPPORT",
        toast_wait: "Connecting to the stars...",
        toast_success: "Success!",
        toast_error: "Error connecting to the stars",
        toast_no_energy: "Not enough energy!",
        toast_enter_q: "Formulate your question",
        toast_enter_name: "Enter your name",
        toast_enter_date: "Enter the full date",
        toast_enter_city: "Enter the date and city",
        toast_describe_dream: "Describe your dream first",
        toast_copied: "Link copied!",
        toast_cleared: "Chat cleared",
        toast_lang_changed: "Language changed ✓"
    },
    es: {
        loading: "Sincronizando con las estrellas...",
        back: "Volver",
        to_main: "Al Inicio",
        save: "GUARDAR",
        cancel: "Cancelar",
        delete: "Eliminar",
        free: "Gratis",
        day: "Día",
        days: "días",
        month: "Mes",
        year: "AAAA",
        nav_home: "Inicio",
        nav_spreads: "Tiradas",
        nav_chats: "Chats",
        nav_shop: "Tienda",
        nav_profile: "Perfil",
        lunar_day_badge: "día lunar",
        home_ready: "Las estrellas están listas,",
        home_wanderer: "Viajero",
        daily_bonus: "Bono Diario",
        bonus_desc: "Entra todos los días",
        energy_day: "Energía del Día",
        toast_invalid_date: "Fecha no válida. ¡Revisa los números!",
        card_day: "Tu Carta del Día",
        card_day_desc: "El universo tiene un mensaje. Ábrelo para saber.",
        opportunities: "OPORTUNIDADES",
        tarot: "Tarot",
        tarot_desc: "Tiradas y análisis",
        astro: "Astrología",
        astro_desc: "Carta natal",
        dreams: "Sueños",
        dreams_desc: "Interpretación de símbolos",
        cal: "Calendario",
        cal_desc: "Fases lunares",
        spreads_title: "Tiradas de Tarot",
        spreads_subtitle: "Elige una tirada. El Tarotista IA descifrará el mensaje.",
        spreads_basic: "BÁSICAS",
        spreads_deep: "PROFUNDAS",
        s1_name: "Carta del Día / Sí-No",
        s1_desc: "Respuesta rápida a una pregunta",
        s2_name: "Pasado · Presente · Futuro",
        s2_desc: "Desarrollo de la situación (3 cartas)",
        s3_name: "Sentimientos",
        s3_desc: "Lo que piensa y siente (3 cartas)",
        s4_name: "Cruz Celta",
        s4_desc: "Análisis detallado de 10 cartas. Causas, efectos y resultado.",
        s5_name: "Problema de Elección",
        s5_desc: "Comparando dos caminos. Te ayuda a decidir.",
        tarot_focus: "Enfoque Mental",
        tarot_arch: "Arquitectura de Tirada",
        cards_count: "carta(s)",
        what_to_ask: "¿Qué quieres preguntar a las estrellas?",
        ph_question: "Describe la situación o haz una pregunta...",
        btn_pull_cards: "SACAR CARTAS",
        shuffling: "Barajando el mazo...",
        shuffling_desc: "Esto toma 15–25 segundos.<br>No cierres la pantalla — las cartas se están alineando.",
        your_question: "Tu pregunta",
        decoding: "Descifrando Estrellas",
        btn_finish: "FINALIZAR RITUAL",
        cal_title: "Energía del Día",
        cal_dos: "Favorable hoy",
        cal_donts: "Evitar hoy",
        cal_beauty: "Belleza y Cuerpo",
        haircut: "Corte de pelo",
        coloring: "Coloración",
        manicure: "Manicura",
        face_care: "Cuidado facial",
        horoscope: "Horóscopo",
        today: "Hoy",
        sign: "Signo",
        dreams_title: "Diario de Sueños",
        dreams_subtitle: "Escribe tu sueño. Nuestra IA, entrenada en Jung, descifrará sus símbolos.",
        ph_dream: "Soñé que estaba de pie al borde de un acantilado...",
        btn_decode: "Descifrar",
        chat_oracle: "Oráculo Universal",
        chat_online: "En línea",
        quick_pred: "🔮 Predicción",
        quick_astro: "✨ Pronóstico Astro",
        ph_chat: "Pregunta al Oráculo...",
        shop_title: "Energía Estelar",
        shop_subtitle: "Cristales de energía pura para tiradas profundas y hablar con el Oráculo",
        shop_empty: "La vitrina está vacía",
        shop_empty_desc: "Los cristales de energía aún se están formando...",
        energy_unit: "Energía",
        prof_with_us: "Con nosotros desde",
        prof_sign: "SIGNO",
        prof_element: "ELEMENTO",
        prof_planet: "PLANETA",
        prof_streak: "RACHA",
        prof_balance: "SALDO",
        ref_title: "Programa de Referidos",
        ref_desc: "Invita amigos y obtén bonos",
        prof_settings: "AJUSTES",
        prof_name: "Nombre",
        prof_birth: "Datos de Nacimiento",
        prof_add: "Añadir",
        prof_lang: "Idioma de la App",
        prof_support: "Ayuda y Soporte",
        prof_terms: "Términos y Políticas",
        prof_unknown: "Desconocido",
        bonus_welcome: "Bienvenido de nuevo",
        bonus_streak: "Días en flujo",
        bonus_of: "de 7",
        bonus_keep: "Gran inercia. ¡Sigue así!",
        bonus_all: "RECOMPENSAS",
        bonus_claimed: "Reclamado",
        bonus_claim: "Reclamar",
        card_energy: "Energía Diaria",
        card_pull: "Sacar Carta",
        card_guide: "Guía Principal del Día",
        card_time: "Hora de Poder",
        card_vibe: "Vibración",
        card_sync: "Sintonía",
        card_back: "Volver a Constelaciones",
        card_wait: "El Oráculo ajusta las frecuencias astrales...",
        card_ready: "Las estrellas se han alineado en tu espacio",
        card_touch: "Toca el éter para que el Oráculo saque tu Arcano personal.",
        lang_title: "Elige el Idioma",
        birth_title: "Tu Cumpleaños",
        name_title: "¿Cómo deberíamos llamarte?",
        ph_name: "Tu nombre...",
        btn_save_name: "GUARDAR NOMBRE",
        astro_title: "Cosmo-Pasaporte",
        astro_desc: "Proporciona datos exactos para considerar influencias planetarias.",
        time: "Hora",
        dont_know: "No lo sé",
        city: "Ciudad de nacimiento",
        btn_calc_chart: "CALCULAR CARTA",
        ref_friends: "Tus amigos",
        ref_bonus: "Invita amigos y recibe +3 de energía por cada uno",
        ref_link: "Tu enlace",
        ref_share: "Compartir en Telegram",
        ref_invited: "Invitados",
        del_chat_title: "¿Eliminar chat?",
        del_chat_desc: "Todos los mensajes se eliminarán permanentemente. No se puede deshacer.",
        maint_title: "Sobrecarga Cósmica",
        maint_desc: "Conexión interrumpida temporalmente. ¡Lo estamos arreglando! 🛠️",
        maint_btn: "CONTACTAR SOPORTE",
        toast_wait: "Conectando con las estrellas...",
        toast_success: "¡Éxito!",
        toast_error: "Error de conexión",
        toast_no_energy: "¡No hay suficiente energía!",
        toast_enter_q: "Formula tu pregunta",
        toast_enter_name: "Introduce tu nombre",
        toast_enter_date: "Introduce la fecha",
        toast_enter_city: "Introduce fecha y ciudad",
        toast_describe_dream: "Describe tu sueño primero",
        toast_copied: "¡Enlace copiado!",
        toast_cleared: "Chat borrado",
        toast_lang_changed: "Idioma cambiado ✓"
    },
    fr: {
        loading: "Synchronisation...",
        back: "Retour",
        to_main: "Accueil",
        save: "ENREGISTRER",
        cancel: "Annuler",
        delete: "Supprimer",
        free: "Gratuit",
        day: "Jour",
        days: "jours",
        month: "Mois",
        year: "AAAA",
        nav_home: "Accueil",
        nav_spreads: "Tirages",
        nav_chats: "Chats",
        nav_shop: "Boutique",
        nav_profile: "Profil",
        lunar_day_badge: "jour lunaire",
        home_ready: "Les étoiles sont prêtes,",
        home_wanderer: "Voyageur",
        daily_bonus: "Bonus Quotidien",
        bonus_desc: "Connectez-vous tous les jours",
        energy_day: "Énergie du Jour",
        card_day: "Votre Carte du Jour",
        card_day_desc: "L'univers a un message. Ouvrez pour le découvrir.",
        opportunities: "OPPORTUNITÉS",
        tarot: "Tarot",
        tarot_desc: "Tirages et analyse",
        astro: "Astrologie",
        astro_desc: "Thème astral",
        dreams: "Rêves",
        dreams_desc: "Interprétation de symboles",
        cal: "Calendrier",
        cal_desc: "Phases lunaires",
        spreads_title: "Tirages de Tarot",
        spreads_subtitle: "Choisissez un tirage. Le Tarologue IA déchiffrera le message.",
        spreads_basic: "BASIQUES",
        spreads_deep: "PROFONDS",
        toast_invalid_date: "Date invalide. Vérifiez les nombres !",
        s1_name: "Carte du Jour / Oui-Non",
        s1_desc: "Réponse rapide à une question",
        s2_name: "Passé · Présent · Futur",
        s2_desc: "Évolution de la situation (3 cartes)",
        s3_name: "Les Sentiments",
        s3_desc: "Ce qu'il pense et ressent (3 cartes)",
        s4_name: "Croix Celtique",
        s4_desc: "Analyse détaillée de 10 cartes. Causes, effets et résultat.",
        s5_name: "Le Problème du Choix",
        s5_desc: "Comparer deux chemins. Vous aide à décider.",
        tarot_focus: "Concentration Mentale",
        tarot_arch: "Architecture du Tirage",
        cards_count: "carte(s)",
        what_to_ask: "Que voulez-vous demander aux étoiles ?",
        ph_question: "Décrivez la situation ou posez une question...",
        btn_pull_cards: "TIRER LES CARTES",
        shuffling: "Mélange des cartes...",
        shuffling_desc: "Cela prend 15 à 25 secondes.<br>Ne fermez pas l'écran — les cartes s'alignent.",
        your_question: "Votre question",
        decoding: "Déchiffrement des Étoiles",
        btn_finish: "TERMINER LE RITUEL",
        cal_title: "Énergie du Jour",
        cal_dos: "Favorable aujourd'hui",
        cal_donts: "À éviter aujourd'hui",
        cal_beauty: "Beauté & Corps",
        haircut: "Coupe de cheveux",
        coloring: "Coloration",
        manicure: "Manucure",
        face_care: "Soins du visage",
        horoscope: "Horoscope",
        today: "Aujourd'hui",
        sign: "Signe",
        dreams_title: "Journal des Rêves",
        dreams_subtitle: "Écrivez votre rêve. Notre IA, formée sur Jung, déchiffrera ses symboles.",
        ph_dream: "J'ai rêvé que je me tenais au bord d'une falaise...",
        btn_decode: "Déchiffrer",
        chat_oracle: "Oracle Universel",
        chat_online: "En ligne",
        quick_pred: "🔮 Prédiction",
        quick_astro: "✨ Prévisions Astro",
        ph_chat: "Demandez à l'Oracle...",
        shop_title: "Énergie Stellaire",
        shop_subtitle: "Cristaux d'énergie pure pour des tirages profonds",
        shop_empty: "La vitrine est vide",
        shop_empty_desc: "Les cristaux d'énergie sont encore en formation...",
        energy_unit: "Énergie",
        prof_with_us: "Avec nous depuis",
        prof_sign: "SIGNE",
        prof_element: "ÉLÉMENT",
        prof_planet: "PLANÈTE",
        prof_streak: "SÉRIE",
        prof_balance: "SOLDE",
        ref_title: "Programme de Parrainage",
        ref_desc: "Invitez des amis et obtenez des bonus",
        prof_settings: "PARAMÈTRES",
        prof_name: "Nom",
        prof_birth: "Données de Naissance",
        prof_add: "Ajouter",
        prof_lang: "Langue de l'App",
        prof_support: "Aide & Support",
        prof_terms: "Conditions et Politiques",
        prof_unknown: "Inconnu",
        bonus_welcome: "Bon retour",
        bonus_streak: "Jours en flux",
        bonus_of: "sur 7",
        bonus_keep: "Excellente dynamique. Continuez !",
        bonus_all: "RÉCOMPENSAS",
        bonus_claimed: "Réclamé",
        bonus_claim: "Réclamer",
        card_energy: "Énergie Quotidienne",
        card_pull: "Tirer la Carte",
        card_guide: "Guide Principal du Jour",
        card_time: "Heure de Pouvoir",
        card_vibe: "Vibration",
        card_sync: "Alignement",
        card_back: "Retour aux Constellations",
        card_wait: "L'Oracle ajuste les fréquences astrales...",
        card_ready: "Les étoiles se sont alignées",
        card_touch: "Touchez l'éther pour que l'Oracle tire votre Arcane personnel.",
        lang_title: "Choisissez la Langue",
        birth_title: "Votre Anniversaire",
        name_title: "Comment devrions-nous vous appeler ?",
        ph_name: "Votre nom...",
        btn_save_name: "ENREGISTRER LE NOM",
        astro_title: "Cosmo-Passeport",
        astro_desc: "Fournissez des données exactes pour l'IA.",
        time: "Heure",
        dont_know: "Je ne sais pas",
        city: "Ville de naissance",
        btn_calc_chart: "CALCULER LE THÈME",
        ref_friends: "Vos amis",
        ref_bonus: "Invitez des amis et recevez +3 d'énergie pour chacun",
        ref_link: "Votre lien",
        ref_share: "Partager sur Telegram",
        ref_invited: "Invités",
        del_chat_title: "Supprimer le chat ?",
        del_chat_desc: "Tous les messages seront définitivement supprimés.",
        maint_title: "Surcharge Cosmique",
        maint_desc: "Connexion interrompue temporairement. Nous réparons cela ! 🛠️",
        maint_btn: "CONTACTER LE SUPPORT",
        toast_wait: "Connexion aux étoiles...",
        toast_success: "Succès !",
        toast_error: "Erreur de connexion",
        toast_no_energy: "Pas assez d'énergie !",
        toast_enter_q: "Formulez votre question",
        toast_enter_name: "Entrez votre nom",
        toast_enter_date: "Entrez la date",
        toast_enter_city: "Entrez date et ville",
        toast_describe_dream: "Décrivez d'abord votre rêve",
        toast_copied: "Lien copié !",
        toast_cleared: "Chat effacé",
        toast_lang_changed: "Langue modifiée ✓"
    },
    de: {
        loading: "Synchronisation...",
        back: "Zurück",
        to_main: "Zur Startseite",
        save: "SPEICHERN",
        cancel: "Abbrechen",
        delete: "Löschen",
        free: "Kostenlos",
        day: "Tag",
        days: "Tage",
        month: "Monat",
        year: "JJJJ",
        nav_home: "Startseite",
        nav_spreads: "Legungen",
        nav_chats: "Chats",
        nav_shop: "Shop",
        nav_profile: "Profil",
        lunar_day_badge: "Mondtag",
        home_ready: "Die Sterne sind bereit,",
        home_wanderer: "Wanderer",
        daily_bonus: "Täglicher Bonus",
        bonus_desc: "Logge dich jeden Tag ein",
        energy_day: "Energie des Tages",
        card_day: "Deine Tageskarte",
        card_day_desc: "Das Universum hat eine Nachricht. Öffnen, um sie zu sehen.",
        opportunities: "MÖGLICHKEITEN",
        tarot: "Tarot",
        tarot_desc: "Legungen und Analysen",
        astro: "Astrologie",
        astro_desc: "Geburtshoroskop",
        dreams: "Träume",
        dreams_desc: "Symboldeutung",
        cal: "Kalender",
        cal_desc: "Mondphasen",
        spreads_title: "Tarot-Legungen",
        spreads_subtitle: "Wähle eine Legung. Der KI-Tarotleser entschlüsselt die Nachricht.",
        spreads_basic: "BASIS",
        spreads_deep: "TIEFGRÜNDIG",
        s1_name: "Tageskarte / Ja-Nein",
        s1_desc: "Schnelle Antwort auf eine Frage",
        s2_name: "Vergangenheit · Gegenwart · Zukunft",
        s2_desc: "Entwicklung der Situation (3 Karten)",
        s3_name: "Gefühle einer Person",
        s3_desc: "Was sie denkt und fühlt (3 Karten)",
        s4_name: "Keltisches Kreuz",
        s4_desc: "Detaillierte Analyse von 10 Karten. Ursachen, Wirkungen und Ergebnis.",
        s5_name: "Das Problem der Wahl",
        s5_desc: "Zwei Wege vergleichen. Hilft bei der Entscheidung.",
        tarot_focus: "Mentaler Fokus",
        tarot_arch: "Struktur der Legung",
        cards_count: "Karte(n)",
        what_to_ask: "Was möchtest du die Sterne fragen?",
        ph_question: "Beschreibe die Situation oder stelle eine Frage...",
        btn_pull_cards: "KARTEN ZIEHEN",
        toast_invalid_date: "Ungültiges Datum. Überprüfe die Zahlen!",
        shuffling: "Mische das Deck...",
        shuffling_desc: "Das dauert 15–25 Sekunden.<br>Schließe nicht den Bildschirm — die Karten richten sich aus.",
        your_question: "Deine Frage",
        decoding: "Sterne entschlüsseln",
        btn_finish: "RITUAL BEENDEN",
        cal_title: "Energie des Tages",
        cal_dos: "Günstig heute",
        cal_donts: "Heute vermeiden",
        cal_beauty: "Schönheit & Körper",
        haircut: "Haarschnitt",
        coloring: "Haare färben",
        manicure: "Maniküre",
        face_care: "Gesichtspflege",
        horoscope: "Horoskop",
        today: "Heute",
        sign: "Sternzeichen",
        dreams_title: "Traum-Tagebuch",
        dreams_subtitle: "Schreibe deinen Traum auf. Unsere KI wird seine Symbole entschlüsseln.",
        ph_dream: "Ich träumte, ich stünde am Rand einer Klippe...",
        btn_decode: "Entschlüsseln",
        chat_oracle: "Universelles Orakel",
        chat_online: "Online",
        quick_pred: "🔮 Vorhersage",
        quick_astro: "✨ Astro-Prognose",
        ph_chat: "Frag das Orakel...",
        shop_title: "Sternenenergie",
        shop_subtitle: "Kristalle reiner Energie für tiefe Legungen",
        shop_empty: "Die Vitrine ist leer",
        shop_empty_desc: "Energiekristalle bilden sich noch...",
        energy_unit: "Energie",
        prof_with_us: "Bei uns seit",
        prof_sign: "ZEICHEN",
        prof_element: "ELEMENT",
        prof_planet: "PLANET",
        prof_streak: "STREAK",
        prof_balance: "GUTHABEN",
        ref_title: "Empfehlungsprogramm",
        ref_desc: "Lade Freunde ein und erhalte Boni",
        prof_settings: "EINSTELLUNGEN",
        prof_name: "Name",
        prof_birth: "Geburtsdaten",
        prof_add: "Hinzufügen",
        prof_lang: "App-Sprache",
        prof_support: "Hilfe & Support",
        prof_terms: "Bedingungen und Richtlinien",
        prof_unknown: "Unbekannt",
        bonus_welcome: "Willkommen zurück",
        bonus_streak: "Tage im Fluss",
        bonus_of: "von 7",
        bonus_keep: "Tolle Dynamik. Mach weiter so!",
        bonus_all: "BELOHNUNGEN",
        bonus_claimed: "Beansprucht",
        bonus_claim: "Beanspruchen",
        card_energy: "Tagesenergie",
        card_pull: "Karte ziehen",
        card_guide: "Hauptleitfaden des Tages",
        card_time: "Stunde der Macht",
        card_vibe: "Schwingung",
        card_sync: "Ausrichtung",
        card_back: "Zurück zu den Konstellationen",
        card_wait: "Das Orakel stellt astrale Frequenzen ein...",
        card_ready: "Die Sterne haben sich ausgerichtet",
        card_touch: "Berühre den Äther, damit das Orakel deine persönliche Arkana zieht.",
        lang_title: "Sprache wählen",
        birth_title: "Dein Geburtstag",
        name_title: "Wie sollen wir dich nennen?",
        ph_name: "Dein Name...",
        btn_save_name: "NAME SPEICHERN",
        astro_title: "Kosmo-Pass",
        astro_desc: "Gib genaue Daten für die KI an.",
        time: "Zeit",
        dont_know: "Weiß ich nicht",
        city: "Geburtsstadt",
        btn_calc_chart: "HOROSKOP BERECHNEN",
        ref_friends: "Deine Freunde",
        ref_bonus: "Lade Freunde ein und erhalte +3 Energie für jeden",
        ref_link: "Dein Link",
        ref_share: "In Telegram teilen",
        ref_invited: "Eingeladen",
        del_chat_title: "Chat löschen?",
        del_chat_desc: "Alle Nachrichten werden dauerhaft gelöscht.",
        maint_title: "Kosmische Überlastung",
        maint_desc: "Verbindung vorübergehend unterbrochen. Wir beheben das! 🛠️",
        maint_btn: "SUPPORT KONTAKTIEREN",
        toast_wait: "Verbindung zu den Sternen...",
        toast_success: "Erfolg!",
        toast_error: "Verbindungsfehler",
        toast_no_energy: "Nicht genug Energie!",
        toast_enter_q: "Formuliere deine Frage",
        toast_enter_name: "Gib deinen Namen ein",
        toast_enter_date: "Gib das Datum ein",
        toast_enter_city: "Datum und Stadt eingeben",
        toast_describe_dream: "Beschreibe zuerst deinen Traum",
        toast_copied: "Link kopiert!",
        toast_cleared: "Chat gelöscht",
        toast_lang_changed: "Sprache geändert ✓"
    }
};





// === СЛОВАРЬ АСТРОЛОГИЧЕСКИХ ТЕРМИНОВ ===
const astroDict = {
    'ru': {
        signs: ["Овен", "Телец", "Близнецы", "Рак", "Лев", "Дева", "Весы", "Скорпион", "Стрелец", "Козерог", "Водолей", "Рыбы"],
        elements: ["Огонь", "Земля", "Воздух", "Вода"],
        planets: ["Марс", "Венера", "Меркурий", "Луна", "Солнце", "Плутон", "Юпитер", "Сатурн", "Уран", "Нептун"]
    },
    'en': {
        signs: ["Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo", "Libra", "Scorpio", "Sagittarius", "Capricorn", "Aquarius", "Pisces"],
        elements: ["Fire", "Earth", "Air", "Water"],
        planets: ["Mars", "Venus", "Mercury", "Moon", "Sun", "Pluto", "Jupiter", "Saturn", "Uranus", "Neptune"]
    },
    'es': {
        signs: ["Aries", "Tauro", "Géminis", "Cáncer", "Leo", "Virgo", "Libra", "Escorpio", "Sagitario", "Capricornio", "Acuario", "Piscis"],
        elements: ["Fuego", "Tierra", "Aire", "Agua"],
        planets: ["Marte", "Venus", "Mercurio", "Luna", "Sol", "Plutón", "Júpiter", "Saturno", "Urano", "Neptuno"]
    },
    'fr': {
        signs: ["Bélier", "Taureau", "Gémeaux", "Cancer", "Lion", "Vierge", "Balance", "Scorpion", "Sagittaire", "Capricorne", "Verseau", "Poissons"],
        elements: ["Feu", "Terre", "Air", "Eau"],
        planets: ["Mars", "Vénus", "Mercure", "Lune", "Soleil", "Pluton", "Jupiter", "Saturne", "Uranus", "Neptune"]
    },
    'de': {
        signs: ["Widder", "Stier", "Zwillinge", "Krebs", "Löwe", "Jungfrau", "Waage", "Skorpion", "Schütze", "Steinbock", "Wassermann", "Fische"],
        elements: ["Feuer", "Erde", "Luft", "Wasser"],
        planets: ["Mars", "Venus", "Merkur", "Mond", "Sonne", "Pluto", "Jupiter", "Saturn", "Uranus", "Neptun"]
    }
};

const zodiacEmojis = ["♈", "♉", "♊", "♋", "♌", "♍", "♎", "♏", "♐", "♑", "♒", "♓"];

// === БАЗА ЗНАНИЙ ДЛЯ МОДАЛОК (МГНОВЕННАЯ ГЕНЕРАЦИЯ) ===
const astroDescriptions = {
    'ru': {
        'sign': [
            "<b>Овен</b> — первооткрыватель и лидер. Вы обладаете неукротимой энергией, бесстрашием и страстью. Ваш кармический путь — вести за собой, не боясь преград.",
            "<b>Телец</b> — символ надежности. Вы цените комфорт, красоту и стабильность. Ваша суперсила — упорство, способное воплотить любые мечты в реальность.",
            "<b>Близнецы</b> — вечные искатели. Вы гибки, умны и невероятно общительны. Ваша миссия — передавать информацию и связывать людей друг с другом.",
            "<b>Рак</b> — хранитель эмоций. У вас глубочайшая эмпатия и сильная интуиция. Ваша сила в умении заботиться, исцелять души и создавать уют.",
            "<b>Лев</b> — яркая звезда. Вы рождены, чтобы сиять, творить и дарить тепло. В вас заложена мощная творческая энергия и врожденное благородство.",
            "<b>Дева</b> — мастер порядка. Вы обладаете аналитическим умом и вниманием к деталям. Ваша задача — совершенствовать этот мир и приносить реальную пользу.",
            "<b>Весы</b> — миротворцы. Вы стремитесь к балансу, эстетике и гармонии в отношениях. Ваша сила — в дипломатии и умении видеть красоту во всем.",
            "<b>Скорпион</b> — алхимик душ. Вы обладаете магнетизмом и способностью к глубокой трансформации. Вы не боитесь кризисов, ведь они делают вас сильнее.",
            "<b>Стрелец</b> — философ и путешественник. Вы полны оптимизма и жажды познания. Ваш путь — расширять горизонты и вдохновлять других своими идеями.",
            "<b>Козерог</b> — стратег. Вы невероятно целеустремленны, дисциплинированны и выносливы. Ваша карма — достигать вершин, которые другим не под силу.",
            "<b>Водолей</b> — бунтарь и новатор. Вы мыслите категориями будущего и свободы. Ваша миссия — ломать старые рамки и приносить в мир гениальные идеи.",
            "<b>Рыбы</b> — мистики. У вас тончайшая связь с космосом и миром снов. Вы способны чувствовать то, что скрыто от глаз, и исцелять через искусство."
        ],
        'element': [
            "<b>Огонь</b> — это искра жизни. Твоя стихия наделяет тебя энтузиазмом, харизмой и способностью зажигать сердца других. Ты действуешь быстро и по зову страсти.",
            "<b>Земля</b> — это фундамент. Твоя стихия дает тебе практичность, устойчивость и умение материализовать свои планы. На тебя всегда можно опереться.",
            "<b>Воздух</b> — это интеллект. Твоя стихия связана с идеями, общением и свободой мыслей. Ты легко адаптируешься и всегда находишь новые решения.",
            "<b>Вода</b> — это глубина. Твоя стихия отвечает за интуицию, эмоции и подсознание. Ты чувствуешь мир на уровне вибраций и скрытых смыслов."
        ],
        'planet': [
            "<b>Марс</b> — планета воинов. Она отвечает за твою пробивную силу, амбиции и умение постоять за себя в любой ситуации.",
            "<b>Венера</b> — планета любви. Она наделяет тебя магнетизмом, чувством прекрасного и талантом выстраивать гармоничные отношения.",
            "<b>Меркурий</b> — планета интеллекта. Твоя суперсила — быстрый ум, логика, красноречие и способность легко усваивать знания.",
            "<b>Луна</b> — светило подсознания. Она делает тебя глубоко чувствующим человеком, дарит сильную интуицию и связь с предками.",
            "<b>Солнце</b> — центр системы. Оно дает тебе неиссякаемый источник жизненной энергии, харизму и желание светить другим.",
            "<b>Плутон</b> — планета трансформации. Она наделяет тебя скрытой мощью, умением управлять толпой и возрождаться из пепла.",
            "<b>Юпитер</b> — планета большого счастья. Она приносит тебе удачу, стремление к развитию, авторитет и широту взглядов.",
            "<b>Сатурн</b> — планета кармы. Она учит тебя дисциплине, дает стальной стержень внутри и помогает добиваться целей упорным трудом.",
            "<b>Уран</b> — планета будущего. Она дарит тебе нестандартное мышление, тягу к свободе, бунтарство и гениальные озарения.",
            "<b>Нептун</b> — планета иллюзий. Она дает тебе мощные экстрасенсорные способности, талант к творчеству и связь с тонкими мирами."
        ]
    },
    'en': {
        'sign': [
            "<b>Aries</b> — the pioneer and leader. You possess indomitable energy, fearlessness, and passion. Your karmic path is to lead, unafraid of obstacles.",
            "<b>Taurus</b> — the symbol of reliability. You value comfort, beauty, and stability. Your superpower is persistence, capable of turning any dream into reality.",
            "<b>Gemini</b> — eternal seekers. You are flexible, smart, and incredibly sociable. Your mission is to transmit information and connect people with each other.",
            "<b>Cancer</b> — the guardian of emotions. You have profound empathy and strong intuition. Your strength lies in the ability to care, heal souls, and create comfort.",
            "<b>Leo</b> — a bright star. You were born to shine, create, and give warmth. You hold a powerful creative energy and innate nobility.",
            "<b>Virgo</b> — the master of order. You possess an analytical mind and attention to detail. Your task is to perfect this world and bring real value.",
            "<b>Libra</b> — the peacemakers. You strive for balance, aesthetics, and harmony in relationships. Your strength is in diplomacy and the ability to see beauty in everything.",
            "<b>Scorpio</b> — the alchemist of souls. You possess magnetism and the capacity for deep transformation. You don't fear crises, because they make you stronger.",
            "<b>Sagittarius</b> — the philosopher and traveler. You are full of optimism and a thirst for knowledge. Your path is to expand horizons and inspire others with your ideas.",
            "<b>Capricorn</b> — the strategist. You are incredibly purposeful, disciplined, and resilient. Your karma is to reach heights that others cannot.",
            "<b>Aquarius</b> — the rebel and innovator. You think in terms of the future and freedom. Your mission is to break old boundaries and bring brilliant ideas to the world.",
            "<b>Pisces</b> — the mystics. You have a subtle connection with the cosmos and the world of dreams. You can feel what is hidden from the eyes and heal through art."
        ],
        'element': [
            "<b>Fire</b> — the spark of life. Your element endows you with enthusiasm, charisma, and the ability to ignite the hearts of others. You act quickly and follow your passion.",
            "<b>Earth</b> — the foundation. Your element gives you practicality, stability, and the ability to materialize your plans. You are someone others can always rely on.",
            "<b>Air</b> — the intellect. Your element is associated with ideas, communication, and freedom of thought. You adapt easily and always find new solutions.",
            "<b>Water</b> — the depth. Your element governs intuition, emotions, and the subconscious. You feel the world on the level of vibrations and hidden meanings."
        ],
        'planet': [
            "<b>Mars</b> — the planet of warriors. It governs your breakthrough power, ambitions, and the ability to stand up for yourself in any situation.",
            "<b>Venus</b> — the planet of love. It endows you with magnetism, a sense of beauty, and the talent to build harmonious relationships.",
            "<b>Mercury</b> — the planet of intellect. Your superpower is a quick mind, logic, eloquence, and the ability to easily absorb knowledge.",
            "<b>Moon</b> — the luminary of the subconscious. It makes you a deeply feeling person, grants strong intuition, and a connection with ancestors.",
            "<b>Sun</b> — the center of the system. It gives you an inexhaustible source of vital energy, charisma, and the desire to shine for others.",
            "<b>Pluto</b> — the planet of transformation. It endows you with hidden power, the ability to control crowds, and to rise from the ashes.",
            "<b>Jupiter</b> — the planet of great happiness. It brings you luck, a drive for development, authority, and broad-mindedness.",
            "<b>Saturn</b> — the planet of karma. It teaches you discipline, gives you an inner core of steel, and helps you achieve your goals through hard work.",
            "<b>Uranus</b> — the planet of the future. It grants you unconventional thinking, a craving for freedom, rebelliousness, and brilliant insights.",
            "<b>Neptune</b> — the planet of illusions. It gives you powerful extrasensory abilities, a talent for creativity, and a connection to subtle worlds."
        ]
    },
    'es': {
        'sign': [
            "<b>Aries</b> — el pionero y líder. Posees una energía indomable, valentía y pasión. Tu camino kármico es liderar sin temor a los obstáculos.",
            "<b>Tauro</b> — el símbolo de la fiabilidad. Valoras el confort, la belleza y la estabilidad. Tu superpoder es la perseverancia, capaz de hacer realidad cualquier sueño.",
            "<b>Géminis</b> — los eternos buscadores. Eres flexible, inteligente e increíblemente sociable. Tu misión es transmitir información y conectar a las personas.",
            "<b>Cáncer</b> — el guardián de las emociones. Tienes una profunda empatía y una fuerte intuición. Tu fuerza radica en la capacidad de cuidar, sanar almas y crear confort.",
            "<b>Leo</b> — una estrella brillante. Naciste para brillar, crear y dar calor. Llevas una poderosa energía creativa y una nobleza innata.",
            "<b>Virgo</b> — el maestro del orden. Posees una mente analítica y atención al detalle. Tu tarea es perfeccionar este mundo y aportar un valor real.",
            "<b>Libra</b> — los pacificadores. Buscas el equilibrio, la estética y la armonía en las relaciones. Tu fuerza está en la diplomacia y en la capacidad de ver la belleza en todo.",
            "<b>Escorpio</b> — el alquimista de las almas. Posees magnetismo y capacidad para una profunda transformación. No temes a las crisis, porque te hacen más fuerte.",
            "<b>Sagitario</b> — el filósofo y viajero. Estás lleno de optimismo y sed de conocimiento. Tu camino es expandir horizontes e inspirar a otros con tus ideas.",
            "<b>Capricornio</b> — el estratega. Eres increíblemente decidido, disciplinado y resistente. Tu karma es alcanzar cimas que otros no pueden.",
            "<b>Acuario</b> — el rebelde e innovador. Piensas en términos de futuro y libertad. Tu misión es romper los viejos límites y traer ideas brillantes al mundo.",
            "<b>Piscis</b> — los místicos. Tienes una sutil conexión con el cosmos y el mundo de los sueños. Puedes sentir lo que está oculto a los ojos y sanar a través del arte."
        ],
        'element': [
            "<b>Fuego</b> — la chispa de la vida. Tu elemento te dota de entusiasmo, carisma y la capacidad de encender los corazones de los demás. Actúas rápido y sigues tu pasión.",
            "<b>Tierra</b> — los cimientos. Tu elemento te da sentido práctico, estabilidad y la capacidad de materializar tus planes. Eres alguien en quien los demás siempre pueden confiar.",
            "<b>Aire</b> — el intelecto. Tu elemento se asocia a las ideas, la comunicación y la libertad de pensamiento. Te adaptas fácilmente y siempre encuentras nuevas soluciones.",
            "<b>Agua</b> — la profundidad. Tu elemento rige la intuición, las emociones y el subconsciente. Sientes el mundo a nivel de vibraciones y significados ocultos."
        ],
        'planet': [
            "<b>Marte</b> — el planeta de los guerreros. Rige tu poder de superación, tus ambiciones y tu capacidad para defenderte en cualquier situación.",
            "<b>Venus</b> — el planeta del amor. Te dota de magnetismo, sentido de la belleza y talento para construir relaciones armoniosas.",
            "<b>Mercurio</b> — el planeta del intelecto. Tu superpoder es una mente rápida, la lógica, la elocuencia y la capacidad de absorber conocimientos fácilmente.",
            "<b>Luna</b> — el astro del subconsciente. Te hace una persona de sentimientos profundos, te otorga una fuerte intuición y conexión con los ancestros.",
            "<b>Sol</b> — el centro del sistema. Te da una fuente inagotable de energía vital, carisma y el deseo de brillar para los demás.",
            "<b>Plutón</b> — el planeta de la transformación. Te dota de un poder oculto, la capacidad de controlar multitudes y resurgir de las cenizas.",
            "<b>Júpiter</b> — el planeta de la gran felicidad. Te trae suerte, un impulso de desarrollo, autoridad y amplitud de miras.",
            "<b>Saturno</b> — el planeta del karma. Te enseña disciplina, te da un núcleo interior de acero y te ayuda a alcanzar tus metas con trabajo duro.",
            "<b>Urano</b> — el planeta del futuro. Te otorga un pensamiento no convencional, ansias de libertad, rebeldía y percepciones brillantes.",
            "<b>Neptuno</b> — el planeta de las ilusiones. Te da poderosas habilidades extrasensoriales, talento para la creatividad y una conexión con los mundos sutiles."
        ]
    },
    'fr': {
        'sign': [
            "<b>Bélier</b> — le pionnier et le leader. Tu possèdes une énergie indomptable, de l'intrépidité et de la passion. Ton chemin karmique est de diriger, sans craindre les obstacles.",
            "<b>Taureau</b> — le symbole de la fiabilité. Tu apprécies le confort, la beauté et la stabilité. Ton superpouvoir est la persévérance, capable de transformer n'importe quel rêve en réalité.",
            "<b>Gémeaux</b> — les éternels chercheurs. Tu es flexible, intelligent et incroyablement sociable. Ta mission est de transmettre l'information et de connecter les gens entre eux.",
            "<b>Cancer</b> — le gardien des émotions. Tu as une empathie profonde et une forte intuition. Ta force réside dans la capacité à prendre soin, à guérir les âmes et à créer du confort.",
            "<b>Lion</b> — une étoile brillante. Tu es né pour briller, créer et donner de la chaleur. Tu possèdes une puissante énergie créative et une noblesse innée.",
            "<b>Vierge</b> — le maître de l'ordre. Tu possèdes un esprit analytique et le sens du détail. Ta tâche est de perfectionner ce monde et d'apporter une valeur réelle.",
            "<b>Balance</b> — les artisans de la paix. Tu recherches l'équilibre, l'esthétique et l'harmonie dans les relations. Ta force réside dans la diplomatie et la capacité à voir la beauté en tout.",
            "<b>Scorpion</b> — l'alchimiste des âmes. Tu possèdes du magnétisme et la capacité d'une profonde transformation. Tu ne crains pas les crises, car elles te rendent plus fort.",
            "<b>Sagittaire</b> — le philosophe et voyageur. Tu es plein d'optimisme et de soif de connaissances. Ton chemin est d'élargir les horizons et d'inspirer les autres avec tes idées.",
            "<b>Capricorne</b> — le stratège. Tu es incroyablement déterminé, discipliné et résistant. Ton karma est d'atteindre des sommets que les autres ne peuvent pas.",
            "<b>Verseau</b> — le rebelle et l'innovateur. Tu penses en termes d'avenir et de liberté. Ta mission est de briser les anciennes limites et d'apporter des idées brillantes au monde.",
            "<b>Poissons</b> — les mystiques. Tu as une connexion subtile avec le cosmos et le monde des rêves. Tu peux ressentir ce qui est caché aux yeux et guérir par l'art."
        ],
        'element': [
            "<b>Feu</b> — l'étincelle de la vie. Ton élément te dota d'enthousiasme, de charisme et de la capacité d'enflammer le cœur des autres. Tu agis rapidement et suis ta passion.",
            "<b>Terre</b> — les fondations. Ton élément te donne un sens pratique, de la stabilité et la capacité de matérialiser tes projets. Tu es quelqu'un sur qui les autres peuvent toujours compter.",
            "<b>Air</b> — l'intellect. Ton élément est associé aux idées, à la communication et à la liberté de pensée. Tu t'adaptes facilement et trouves toujours de nouvelles solutions.",
            "<b>Eau</b> — la profondeur. Ton élément régit l'intuition, les émotions et le subconscient. Tu ressens le monde au niveau des vibrations et des significations cachées."
        ],
        'planet': [
            "<b>Mars</b> — la planète des guerriers. Elle régit ta force de percée, tes ambitions et ta capacité à te défendre dans n'importe quelle situation.",
            "<b>Vénus</b> — la planète de l'amour. Elle te dote de magnétisme, d'un sens de la beauté et du talent pour construire des relations harmonieuses.",
            "<b>Mercure</b> — la planète de l'intellect. Ton superpouvoir est un esprit vif, la logique, l'éloquence et la capacité d'absorber facilement les connaissances.",
            "<b>Lune</b> — l'astre du subconscient. Elle fait de toi une personne aux sentiments profonds, accorde une forte intuition et une connexion avec les ancêtres.",
            "<b>Soleil</b> — le centre du système. Il te donne une source inépuisable d'énergie vitale, de charisme et le désir de briller pour les autres.",
            "<b>Pluton</b> — la planète de la transformation. Elle te dote d'un pouvoir caché, de la capacité de contrôler les foules et de renaître de tes cendres.",
            "<b>Jupiter</b> — la planète du grand bonheur. Elle t'apporte la chance, une volonté de développement, de l'autorité et une grande ouverture d'esprit.",
            "<b>Saturne</b> — la planète du karma. Elle t'enseigne la discipline, te donne un noyau intérieur d'acier et t'aide à atteindre tes objectifs par un travail acharné.",
            "<b>Uranus</b> — la planète du futur. Elle t'accorde une pensée non conventionnelle, une soif de liberté, une rébellion et des idées brillantes.",
            "<b>Neptune</b> — la planète des illusions. Elle te donne de puissantes capacités extrasensorielles, un talent pour la créativité et une connexion aux mondes subtils."
        ]
    },
    'de': {
        'sign': [
            "<b>Widder</b> — der Pionier und Führer. Du besitzt unbändige Energie, Furchtlosigkeit und Leidenschaft. Dein karmischer Weg ist es, voranzugehen, ohne Angst vor Hindernissen.",
            "<b>Stier</b> — das Symbol für Zuverlässigkeit. Du schätzt Komfort, Schönheit und Stabilität. Deine Superkraft ist Beharrlichkeit, die in der Lage ist, jeden Traum in die Realität umzusetzen.",
            "<b>Zwillinge</b> — die ewigen Sucher. Du bist flexibel, klug und unglaublich gesellig. Deine Mission ist es, Informationen zu vermitteln und Menschen miteinander zu verbinden.",
            "<b>Krebs</b> — der Wächter der Emotionen. Du hast tiefe Empathie und eine starke Intuition. Deine Stärke liegt in der Fähigkeit, sich zu kümmern, Seelen zu heilen und Geborgenheit zu schaffen.",
            "<b>Löwe</b> — ein heller Stern. Du wurdest geboren, um zu strahlen, zu erschaffen und Wärme zu geben. Du besitzt eine kraftvolle kreative Energie und angeborene Noblesse.",
            "<b>Jungfrau</b> — der Meister der Ordnung. Du besitzt einen analytischen Verstand und Liebe zum Detail. Deine Aufgabe ist es, diese Welt zu perfektionieren und echten Wert zu schaffen.",
            "<b>Waage</b> — die Friedensstifter. Du strebst nach Gleichgewicht, Ästhetik und Harmonie in Beziehungen. Deine Stärke liegt in der Diplomatie und der Fähigkeit, in allem Schönheit zu sehen.",
            "<b>Skorpion</b> — der Alchemist der Seelen. Du besitzt Magnetismus und die Fähigkeit zu tiefer Transformation. Du fürchtest keine Krisen, denn sie machen dich stärker.",
            "<b>Schütze</b> — der Philosoph und Reisende. Du bist voller Optimismus und Wissensdurst. Dein Weg ist es, Horizonte zu erweitern und andere mit deinen Ideen zu inspirieren.",
            "<b>Steinbock</b> — der Stratege. Du bist unglaublich zielstrebig, diszipliniert und widerstandsfähig. Dein Karma ist es, Höhen zu erreichen, die andere nicht schaffen.",
            "<b>Wassermann</b> — der Rebell und Innovator. Du denkst in Kategorien der Zukunft und der Freiheit. Deine Mission ist es, alte Grenzen zu durchbrechen und der Welt brillante Ideen zu bringen.",
            "<b>Fische</b> — die Mystiker. Du hast eine subtile Verbindung zum Kosmos und zur Welt der Träume. Du kannst fühlen, was den Augen verborgen ist, und durch Kunst heilen."
        ],
        'element': [
            "<b>Feuer</b> — der Funke des Lebens. Dein Element verleiht dir Enthusiasmus, Charisma und die Fähigkeit, die Herzen anderer zu entzünden. Du handelst schnell und folgst deiner Leidenschaft.",
            "<b>Erde</b> — das Fundament. Dein Element gibt dir Praktikabilität, Stabilität und die Fähigkeit, deine Pläne zu verwirklichen. Du bist jemand, auf den sich andere immer verlassen können.",
            "<b>Luft</b> — der Intellekt. Dein Element ist mit Ideen, Kommunikation und Gedankenfreiheit verbunden. Du passt dich leicht an und findest immer neue Lösungen.",
            "<b>Wasser</b> — die Tiefe. Dein Element regiert Intuition, Emotionen und das Unterbewusstsein. Du fühlst die Welt auf der Ebene von Vibrationen und verborgenen Bedeutungen."
        ],
        'planet': [
            "<b>Mars</b> — der Planet der Krieger. Er regiert deine Durchschlagskraft, Ambitionen und die Fähigkeit, in jeder Situation für dich selbst einzustehen.",
            "<b>Venus</b> — der Planet der Liebe. Er verleiht dir Magnetismus, einen Sinn für Schönheit und das Talent, harmonische Beziehungen aufzubauen.",
            "<b>Merkur</b> — der Planet des Intellekts. Deine Superkraft ist ein schneller Verstand, Logik, Beredsamkeit und die Fähigkeit, Wissen leicht aufzunehmen.",
            "<b>Mond</b> — das Gestirn des Unterbewusstseins. Er macht dich zu einem tief fühlenden Menschen, gewährt starke Intuition und eine Verbindung zu den Ahnen.",
            "<b>Sonne</b> — das Zentrum des Systems. Sie gibt dir eine unerschöpfliche Quelle an Lebensenergie, Charisma und den Wunsch, für andere zu leuchten.",
            "<b>Pluto</b> — der Planet der Transformation. Er verleiht dir verborgene Macht, die Fähigkeit, Menschenmengen zu kontrollieren, und wie ein Phönix aus der Asche aufzusteigen.",
            "<b>Jupiter</b> — der Planet des großen Glücks. Er bringt dir Glück, einen Drang nach Entwicklung, Autorität und Aufgeschlossenheit.",
            "<b>Saturn</b> — der Planet des Karmas. Er lehrt dich Disziplin, gibt dir einen inneren Kern aus Stahl und hilft dir, deine Ziele durch harte Arbeit zu erreichen.",
            "<b>Uranus</b> — der Planet der Zukunft. Er gewährt dir unkonventionelles Denken, einen Drang nach Freiheit, Rebellentum und brillante Einsichten.",
            "<b>Neptun</b> — der Planet der Illusionen. Er gibt dir mächtige übersinnliche Fähigkeiten, ein Talent für Kreativität und eine Verbindung zu feinstofflichen Welten."
        ]
    }
};
